### ISSUE TITLE
[Patch] Handling of project path

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chris-armstrong/felix-eclipse#15]
```
What steps will reproduce the problem?
1. Import in eclipse a Maven project using m2e
2. Optionally adjust run configuration to include the desired bundle
3. Run felix with felix-eclipse

What is the expected output? What do you see instead?
felix-eclipse fails because Maven projects have a layout like this:
project/.classpath
project/target/classes/META-INF/
felix-eclipse fails because it looks for .classpath in project/target/classes


What version of the product are you using? On what operating system?
Felix-eclipse from trunk (0.2.2, rev 44), eclipse 4.3.2 from Fedora 20 
repositories (Fedora 20)

Please provide any additional information below.
The attached patch differentiates between the project directory and the binary 
output directories. It might be a little naive (it looks for the project 
directory going back from the output directory) but it should not break 
existing functionalities, and it works for me.

```

Original issue reported on code.google.com by `ugi...@gmail.com` on 11 Jun 2014 at 9:01

Attachments:
- [outputDir.patch](https://storage.googleapis.com/google-code-attachments/felix-eclipse/issue-15/comment-0/outputDir.patch)

**Comment by ogattaz** [comment]
I got the same error : the m2e project doesn't contain a .classpath file and this situation isn't managed.

@look at "au.com.forge.eclipse.osgi.urlhandler.impl.EclipseProjectURLHandler.EclipseProjectURLConnection.handleClasspath(File, ZipOutputStream)"

        /**
		 * Handles the entries in the .classpath file.
		 * 
		 * @param projectDirectory
		 * @param outputStream
		 * @throws IOException
		 */
		private void handleClasspath(File projectDirectory,
				ZipOutputStream outputStream) throws IOException {
			File classpathFile = new File(projectDirectory, ".classpath");
			if (!classpathFile.exists() || !classpathFile.isFile())
				throw new IOException(
						"The .classpath file does not exist in the project directory or is not a file.");
			...
		}


We have also to extend the capabilities of the method "calculateNeededClassPath(String)" to calculate the right collection of classpath elements using the target dir (?) of the m2e project

**Comment by chris-armstrong** [comment]
Ok so it seems that m2exclipse suppresses the generation of the .classpath file. The felix-eclipse plugin uses this to know what the classpath is when it assembles a bundle for runtime. 

You need to find an equivalent way of reliably assembling a classpath based on either maven (pom.xml) or m2eclipse metadata. If you can come up with a patch, I'll review it and integrate it. You're alternative is to just create a fake .classpath file to workaround the issue.
