### ISSUE TITLE
NoSuchMethodError when launching Felix 5

### ISSUE THREAD

**Issue by ogattaz** [chris-armstrong/felix-eclipse#18]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.felix.framework.util.StringMap.put(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
    at au.com.forge.felix.eclipse_pde_launcher.impl.EclipsePDEFelixLauncher.main(EclipsePDEFelixLauncher.java:127)
Error stopping framework: java.lang.NullPointerException
java.lang.NullPointerException
    at au.com.forge.felix.eclipse_pde_launcher.impl.EclipsePDEFelixLauncher$1.run(EclipsePDEFelixLauncher.java:95)

**Comment by chris-armstrong** [comment]
Could you please specify:
* Eclipse version
* Felix version
that this relates to?

**Comment by shri22ram** [comment]
Chirs  i too got the above error. 
Eclipse version is 4.5.0
Felix version is 5.2.0
felix-eclipse is 0.2.2
Is it a known behvaiour?

**Comment by chris-armstrong** [comment]
Not that I know of - I don’t really use felix-eclipse for day-to-day work anymore, so errors like this can pass by me. It looks like StringMap is no longer supported in the API (the code may need to be updated to use an alternative method).

Cheers
Chris

**Comment by akkinenirajesh** [comment]
This problem is solved for me by rebuilding the plugins and deploying them again in eclipse. 

I could not identify what is the actual problem. StringMap is still present in and supported.

**Comment by debbabi** [comment]
I my testing environment, even that I have rebuilt the plugins, I had always the same problem. I finished by creating a new plugin that compiles against Felix 5.0 version (It was in this exact version that the parent class of StringMap was changed, from AbstractMap to TreeMap). I created a pullrequest for that (it is an extension of the existing ones).
